SHELL := /bin/bash
PWD_DIR=$(abspath .)

# ---------------------------------------------------------------------------
# Declarative build: include generated config if present.
# Run `make configure SYSTEM=configs/<preset>.toml` to generate .config.mk
# from a system.toml file.  All variables below use ?= so the generated
# config wins when present.
# ---------------------------------------------------------------------------
-include $(PWD_DIR)/.config.mk

KERNEL_VERSION ?= 6.18.51## Linux kernel version to download and build

# Internal: target bitness, set automatically by .config.mk (default: 32)
BITS ?= 32## Target bitness (32 or 64; usually set by configure)

# Host architecture detection
HOST_ARCH := $(shell uname -m)
HOSTCC ?= cc## Host C compiler used to build gen_init_cpio

# Cross-compiler and target ISA selection based on BITS and HOST_ARCH:
#   32-bit: always cross-compile with riscv64-linux-gnu- (works on any host)
#   64-bit: cross-compile with riscv64-linux-gnu- unless running natively on riscv64
ifeq ($(BITS),64)
  ifeq ($(HOST_ARCH),riscv64)
    CROSS_COMPILE ?=
  else
    CROSS_COMPILE ?= riscv64-linux-gnu-
  endif
  RISCV_XLEN  := 64
  RISCV_ISA   ?= rv64imac_zicntr_zicsr_zifencei
  RISCV_ABI   ?= lp64
else
  BITS         := 32
  CROSS_COMPILE ?= riscv64-linux-gnu-
  RISCV_XLEN  := 32
  RISCV_ISA   ?= rv32imac_zicntr_zicsr_zifencei
  RISCV_ABI   ?= ilp32
endif

# Declarative build variables (set by .config.mk or defaults)
SYSTEM_PRESET   ?=## Preset name generated by make configure
SYSTEM_ROOTFS   ?= initramfs## Rootfs type generated by make configure
SYSTEM_COMPRESS ?= gzip## Initramfs compression generated by make configure
SYSTEM_LOADER   ?= qemu## Test loader generated by make configure (qemu or spike)

# Buildroot variant ISA/ABI (set by .config.mk, defaults match RISCV_ISA/ABI)
RISCV_ISA_BUILDROOT ?= $(RISCV_ISA)## ISA used when packaging Buildroot artifacts
RISCV_ABI_BUILDROOT ?= $(RISCV_ABI)## ABI used when packaging Buildroot artifacts

# Kernel variants must not inherit each other's configuration or firmware flags.
KERNEL_VARIANT ?= minimal## Kernel variant: minimal, buildroot or distro
BUILD_ROOT ?= $(PWD_DIR)## Parent directory for kernel/OpenSBI build outputs
DIST_DIR ?= $(PWD_DIR)/dist## Release output directory
RELEASE_BUILD_ROOT ?= $(PWD_DIR)/dist/.release-work## Isolated build cache for the release matrix
RELEASE_RESUME ?= 0## Reuse matching completed packages when set to 1
PACKAGE_TEST_JOBS ?= 2## Concurrent QEMU package tests
KERNEL_TARGETS ?= Image## Kernel build targets (add modules explicitly if needed)
OBJDIR         := $(BUILD_ROOT)/$(if $(filter distro,$(KERNEL_VARIANT)),$(SYSTEM_PRESET)-kernel,$(if $(filter buildroot,$(KERNEL_VARIANT)),buildroot$(BITS)-kernel,build$(BITS)))
OPENSBI_OBJDIR := $(BUILD_ROOT)/opensbi-build$(BITS)$(if $(filter distro,$(KERNEL_VARIANT)),-$(SYSTEM_PRESET),$(if $(filter buildroot,$(KERNEL_VARIANT)),-buildroot,))
KERNEL_VERSION_STAMP := $(OBJDIR)/.kernel-version

# Per-bitness tiny shell initramfs outputs
INITRAMFS_DIR  := $(PWD_DIR)/initramfs$(BITS)
INITRAMFS_CPIO := $(PWD_DIR)/initramfs$(BITS).cpio.gz
INITRAMFS_LIST := $(PWD_DIR)/initramfs$(BITS).list
GEN_INIT_CPIO := $(OBJDIR)/usr/gen_init_cpio

# Spike (riscv-isa-sim) source and build directories
SPIKE_DIR   := $(PWD_DIR)/spike
SPIKE_BUILD := $(PWD_DIR)/spike-build
# Use the locally-built spike when available, fall back to PATH
SPIKE       := $(if $(wildcard $(SPIKE_BUILD)/bin/spike),$(SPIKE_BUILD)/bin/spike,spike)

NPROC     := $(shell nproc)
QEMU_MEM_BUILDROOT ?= 1024## Buildroot QEMU guest RAM in MiB
QEMU_MEM     ?= 1024## QEMU guest RAM in MiB
# Optional: set QEMU_TIMEOUT=N (seconds) to auto-exit after N seconds.
# Default is empty (run until Ctrl-C or guest halts).
QEMU_TIMEOUT ?=## Auto-exit QEMU after N seconds (empty = run until Ctrl-C)
PACKAGE_TEST_TIMEOUT ?= 120## Per-package boot timeout used by test_all (seconds)
SPIKE_MEM    ?= 512## Spike guest RAM in MiB

# Prefix command with timeout if QEMU_TIMEOUT is set
IF_TIMEOUT = $(if $(QEMU_TIMEOUT),timeout $(QEMU_TIMEOUT),)

# Derive kernel major version for download URL (e.g. 6.18.50 -> v6.x, 7.2.3 -> v7.x)
KERNEL_MAJOR := v$(firstword $(subst ., ,$(KERNEL_VERSION))).x

# Release package name and output tarball path
# Include config preset name when available (e.g. linux-riscv-qemu-rv32-v6.18.50)
ifneq ($(SYSTEM_PRESET),)
  RELEASE_NAME    := linux-riscv-$(SYSTEM_PRESET)-v$(KERNEL_VERSION)
else
  RELEASE_NAME    := linux-riscv-$(BITS)-v$(KERNEL_VERSION)
endif
RELEASE_TARBALL := $(DIST_DIR)/$(RELEASE_NAME).tar.gz
# Staging directory under dist/ (cleaned after tarball is created)
RELEASE_STAGING := $(DIST_DIR)/$(RELEASE_NAME)

# Complete release matrix, traversed deterministically by package_all.
SYSTEM_CONFIGS := $(sort $(wildcard $(PWD_DIR)/configs/*.toml))

# Linux kernel source directory (versioned so multiple kernels can coexist)
LINUX_SOURCE_ROOT ?= $(PWD_DIR)/linux## Directory holding versioned upstream Linux sources
LINUX_DIR := $(LINUX_SOURCE_ROOT)/linux-$(KERNEL_VERSION)

# All kernel make invocations use a separate output dir via O=
KERNEL_MAKE := make -C $(LINUX_DIR) O=$(OBJDIR) ARCH=riscv CROSS_COMPILE=$(CROSS_COMPILE) -j$(NPROC)
# scripts/config wrapper that operates on the per-bitness .config
KCONFIG := $(LINUX_DIR)/scripts/config --file $(OBJDIR)/.config

# ---------------------------------------------------------------------------
# Shorthand paths (used throughout targets and error checks)
# ---------------------------------------------------------------------------
KERNEL_IMAGE   := $(OBJDIR)/arch/riscv/boot/Image
FW_PAYLOAD_BIN := $(OPENSBI_OBJDIR)/platform/generic/firmware/fw_payload.bin
FW_PAYLOAD_ELF := $(OPENSBI_OBJDIR)/platform/generic/firmware/fw_payload.elf
FW_DYNAMIC_BIN := $(OPENSBI_OBJDIR)/platform/generic/firmware/fw_dynamic.bin

# Keep the DTB beyond the large embedded Buildroot kernel; matches Raptor stage0.
FW_PAYLOAD_FDT_OFFSET ?= 0x3f00000## DTB offset from firmware base (default: +63 MiB)

# Common OpenSBI make arguments (shared by build_opensbi and build_opensbi_with_kernel)
OPENSBI_MAKE = make -C opensbi \
	O=$(OPENSBI_OBJDIR) \
	PLATFORM_RISCV_ISA=$(RISCV_ISA) \
	CROSS_COMPILE=$(CROSS_COMPILE) \
	PLATFORM_RISCV_XLEN=$(RISCV_XLEN) \
	PLATFORM=generic \
	-j$(NPROC)

# Error-check helpers
#   $(call require,file,hint)      — assert a file exists
#   $(call require_cmd,cmd,hint)   — assert a command is in PATH
define require
	@test -f $(1) || (echo "ERROR: $(notdir $(1)) not found. $(2)" && false)
endef
define require_cmd
	@command -v $(1) >/dev/null 2>&1 || (echo "ERROR: '$(1)' not found. $(2)" && false)
endef

# QEMU kernel boot arguments (split-load mode: fw_dynamic + separate Image + initramfs)
QEMU_KERNEL_ARGS = \
	-bios $(FW_DYNAMIC_BIN) \
	-kernel $(KERNEL_IMAGE) \
	-initrd $(INITRAMFS_CPIO) \
	-append "root=/dev/ram rdinit=/init console=ttyS0 earlycon=sbi ip=dhcp"

# ---------------------------------------------------------------------------
# Buildroot targets and variables (uses variables defined above)
# ---------------------------------------------------------------------------
include scripts/buildroot.mk
include scripts/distro.mk

HELP_FILES := $(filter-out $(PWD_DIR)/.config.mk,$(MAKEFILE_LIST))

# ---------------------------------------------------------------------------
# Help
# ---------------------------------------------------------------------------

# Default target: show usage
.DEFAULT_GOAL := help

help: ## Show generated target and variable help
	@echo "Usage: make <target> [VAR=value ...]"
	@echo ""
	@echo "Current configuration:"
	@printf "  %-18s %s\n" "PWD" "$(PWD_DIR)"
	@printf "  %-18s %s\n" "Kernel" "$(KERNEL_VERSION)"
	@printf "  %-18s %s\n" "Host arch" "$(HOST_ARCH)"
	@printf "  %-18s %s\n" "Target bits" "$(BITS)"
	@printf "  %-18s %s\n" "Cross-compile" "$(if $(CROSS_COMPILE),$(CROSS_COMPILE),(native))"
	@printf "  %-18s %s\n" "Kernel objdir" "$(OBJDIR)"
	@printf "  %-18s %s\n" "Initramfs" "$(INITRAMFS_CPIO)"
	@printf "  %-18s %s\n" "Config" "$(if $(wildcard $(PWD_DIR)/.config.mk),.config.mk loaded,(none; use 'make configure'))"
	@echo ""
	@awk '\
		BEGIN { state=0; pending=""; first_target=1 } \
		function trim(s) { sub(/^[ \t#]+/, "", s); sub(/[ \t]+$$/, "", s); return s } \
		/^# [-=]+$$/ { \
			if (state==0) state=1; \
			else if (state==2) { pending=section; state=0 } \
			else state=0; \
			next } \
		state==1 && /^# [^-=].+/ { section=trim($$0); state=2; next } \
		{ if (state==1) state=0 } \
		/^[[:alnum:]_.%\/-]+:[^=]*##/ { \
			if (pending != "") { printf "\n%s:\n", pending; pending="" } \
			else if (first_target) printf "\nTargets:\n"; \
			first_target=0; \
			target=$$0; sub(/:.*/, "", target); \
			desc=$$0; sub(/^.*##[ \t]*/, "", desc); \
			printf "  %-32s %s\n", target, desc }' $(HELP_FILES)
	@echo ""
	@echo "Variables (override with VAR=value):"
	@awk '\
		function trim(s) { sub(/^[ \t]+/, "", s); sub(/[ \t]+$$/, "", s); return s } \
		/^[ \t]*[A-Z0-9_]+[ \t]*\?=.*##/ { \
			line=$$0; sub(/^[ \t]+/, "", line); \
			name=line; sub(/[ \t]*\?=.*/, "", name); \
			value=line; sub(/^[^?]*\?=/, "", value); sub(/##.*/, "", value); value=trim(value); \
			if (value == "") value="(empty)"; \
			desc=line; sub(/^.*##[ \t]*/, "", desc); \
			printf "  %-22s %-26s %s\n", name, value, desc }' $(HELP_FILES)
	@echo ""
	@echo "Available presets:"
	@for f in configs/*.toml; do echo "  $$f"; done 2>/dev/null

# Alias so 'make all' also prints help (use build_all for actual builds)
all: help ## Alias for help

# ---------------------------------------------------------------------------
# Declarative build targets
# ---------------------------------------------------------------------------
#
# make configure SYSTEM=configs/<preset>.toml   — parse TOML -> .config.{mk,kernel,buildroot}
# make build                                    — full build driven by .config.mk
# make test                                     — boot in QEMU/Spike per config
# make clean_config                             — remove generated .config.* files
#
# All existing imperative targets (build_linux, test_qemu, etc.) remain usable
# and automatically pick up .config.mk overrides when present.
# ---------------------------------------------------------------------------

# Path to system.toml (set on command line: make configure SYSTEM=...)
SYSTEM ?=## TOML preset path for make configure

configure: ## Generate .config.* from SYSTEM=<toml>
	@if [ -z "$(SYSTEM)" ]; then \
		echo "Usage: make configure SYSTEM=configs/<preset>.toml"; \
		echo ""; \
		echo "Available presets:"; \
		ls -1 configs/*.toml 2>/dev/null | sed 's/^/  /'; \
		false; \
	fi
	python3 scripts/gen-config.py $(SYSTEM) --out-dir $(PWD_DIR)
	@echo ""
	@echo "Next: make build"

# Apply generated kernel config fragment via scripts/config
# Usage: $(call apply_kconfig_fragment,/path/to/fragment)
define apply_kconfig_fragment
	@if [ -f $(1) ]; then \
		echo "Applying kernel config fragment: $(1)"; \
		while IFS= read -r line; do \
			case "$$line" in \
				\#\ CONFIG_*\ is\ not\ set) \
					key=$$(echo "$$line" | sed 's/^# \(CONFIG_[A-Za-z0-9_]*\) is not set/\1/'); \
					$(KCONFIG) --disable $$key ;; \
				''|\#*) ;; \
				CONFIG_*=y) \
					key=$$(echo "$$line" | cut -d= -f1); \
					$(KCONFIG) --enable $$key ;; \
				CONFIG_*=*) \
					key=$$(echo "$$line" | cut -d= -f1); \
					val=$$(echo "$$line" | cut -d= -f2- | tr -d '"'); \
					$(KCONFIG) --set-val $$key $$val ;; \
			esac; \
		done < $(1); \
	fi
endef

# Shorthand paths to generated config fragments
KERNEL_CFG          := $(PWD_DIR)/.config.kernel
KERNEL_CFG_MINIMAL  := $(PWD_DIR)/.config.kernel.minimal
KERNEL_CFG_BUILDROOT := $(PWD_DIR)/.config.kernel.buildroot
KERNEL_CFG_DISTRO := $(PWD_DIR)/.config.kernel.distro

# Distribution presets use disk roots; existing presets retain their initramfs paths.
build: linux opensbi ## Build the selected distribution or tiny shell/Buildroot system
ifneq ($(filter alpine debian,$(SYSTEM_ROOTFS)),)
	$(MAKE) build_distro
else
	# --- Tiny shell variant ---
	$(MAKE) build_linux
	$(MAKE) make_initramfs_tiny_shell
	$(MAKE) install_initramfs
	$(MAKE) build_opensbi_with_kernel
	# --- Buildroot variant (if .config.buildroot exists) ---
	@if [ -f $(PWD_DIR)/.config.buildroot ]; then \
		echo "--- Building buildroot variant ---"; \
		$(MAKE) make_initramfs_buildroot; \
	else \
		echo "--- Skipping buildroot (no .config.buildroot) ---"; \
	fi
	@echo ""
	@echo "Build complete.  Run: make test"
endif

# Unified test: boot the configured disk or tiny shell variant.
test: ## Boot the configured system in QEMU or Spike
ifneq ($(filter alpine debian,$(SYSTEM_ROOTFS)),)
	$(MAKE) test_qemu_distro
else ifeq ($(SYSTEM_LOADER),spike)
	$(MAKE) test_spike
else
	$(MAKE) test_qemu_kernel
endif

clean_config: ## Remove generated .config.* files
	rm -f $(PWD_DIR)/.config.mk $(PWD_DIR)/.config.kernel \
	     $(PWD_DIR)/.config.kernel.minimal $(PWD_DIR)/.config.kernel.buildroot \
	     $(PWD_DIR)/.config.kernel.distro \
	     $(PWD_DIR)/.config.buildroot
	@echo "Declarative config removed."

# ---------------------------------------------------------------------------
# Source acquisition
# ---------------------------------------------------------------------------

linux: ## Download and extract Linux kernel source
	python3 scripts/prepare-linux.py --version "$(KERNEL_VERSION)" --source-root "$(LINUX_SOURCE_ROOT)"

opensbi: ## Clone OpenSBI source
	@if [ -d opensbi ]; then echo "opensbi/ already exists, skipping clone"; else \
		git clone https://github.com/riscv-software-src/opensbi; \
	fi

spike_src: ## Clone Spike simulator source
	@if [ -d spike ]; then echo "spike/ already exists, skipping clone"; else \
		git clone https://github.com/riscv-software-src/riscv-isa-sim spike; \
	fi

build_spike: spike_src ## Build and install local Spike simulator
	mkdir -p $(SPIKE_BUILD)
	cd $(SPIKE_BUILD) && $(SPIKE_DIR)/configure --prefix=$(SPIKE_BUILD)
	$(MAKE) -C $(SPIKE_BUILD) -j$(NPROC)
	$(MAKE) -C $(SPIKE_BUILD) install
	@echo "Spike built: $(SPIKE_BUILD)/bin/spike"

# ---------------------------------------------------------------------------
# Kernel build
# ---------------------------------------------------------------------------

configure_kernel: linux ## Generate a fresh shared + variant kernel configuration
	@test "$(KERNEL_VARIANT)" = minimal -o "$(KERNEL_VARIANT)" = buildroot -o "$(KERNEL_VARIANT)" = distro
	@if [ -d "$(OBJDIR)" ] && { [ ! -f "$(KERNEL_VERSION_STAMP)" ] || \
	   [ "$$(cat "$(KERNEL_VERSION_STAMP)" 2>/dev/null)" != "$(KERNEL_VERSION)" ]; }; then \
		echo "Kernel version changed; removing stale $(OBJDIR) output"; \
		rm -rf "$(OBJDIR)"; \
	fi
	mkdir -p $(OBJDIR)
	@printf '%s\n' '$(KERNEL_VERSION)' > $(KERNEL_VERSION_STAMP)
ifeq ($(BITS),32)
	# riscv defconfig is 64-bit; layer the upstream 32-bit overlay to flip
	# ARCH_RV32I/NONPORTABLE cleanly (scripts/config can't drive choice blocks).
	$(KERNEL_MAKE) defconfig 32-bit.config
else
	$(KERNEL_MAKE) defconfig
endif
	# Start from defconfig; apply only the selected variant's fragment.
	$(call apply_kconfig_fragment,$(KERNEL_CFG))
	$(call apply_kconfig_fragment,$(if $(filter distro,$(KERNEL_VARIANT)),$(KERNEL_CFG_DISTRO),$(if $(filter buildroot,$(KERNEL_VARIANT)),$(KERNEL_CFG_BUILDROOT),$(KERNEL_CFG_MINIMAL))))
	$(KERNEL_MAKE) olddefconfig

build_linux: configure_kernel ## Configure and build Linux kernel
	$(KERNEL_MAKE) $(KERNEL_TARGETS)

# ---------------------------------------------------------------------------
# Tiny shell initramfs
# ---------------------------------------------------------------------------

# Build the default /init ELF used by the tiny shell initramfs.
build_init: ## Build tiny shell /init ELF
	make -C payload BITS=$(BITS) CROSS_COMPILE=$(CROSS_COMPILE) tiny_shell

# Calls build_init then packs a rootless initramfs with /init and device nodes.
make_initramfs_tiny_shell: linux ## Build tiny shell initramfs
	$(MAKE) build_init
	mkdir -p $(OBJDIR)/usr
	$(HOSTCC) -O2 -Wall -o $(GEN_INIT_CPIO) $(LINUX_DIR)/usr/gen_init_cpio.c
	@printf '%s\n' \
		'dir /bin 0755 0 0' \
		'dir /dev 0755 0 0' \
		'dir /etc 0755 0 0' \
		'dir /lib 0755 0 0' \
		'dir /lib64 0755 0 0' \
		'dir /mnt 0755 0 0' \
		'dir /mnt/root 0755 0 0' \
		'dir /proc 0755 0 0' \
		'dir /root 0700 0 0' \
		'dir /run 0755 0 0' \
		'dir /sbin 0755 0 0' \
		'dir /sys 0755 0 0' \
		'dir /tmp 1777 0 0' \
		'file /init $(PWD_DIR)/payload/init_shell 0755 0 0' \
		'nod /dev/console 0600 0 0 c 5 1' \
		'nod /dev/null 0666 0 0 c 1 3' \
		'nod /dev/zero 0666 0 0 c 1 5' \
		'nod /dev/tty 0666 0 0 c 5 0' \
		> $(INITRAMFS_LIST)
	$(GEN_INIT_CPIO) $(INITRAMFS_LIST) | gzip > $(INITRAMFS_CPIO)
	@echo "Tiny shell initramfs: $(INITRAMFS_CPIO)"

# ---------------------------------------------------------------------------
# Embed initramfs into kernel Image (CONFIG_INITRAMFS_SOURCE)
# ---------------------------------------------------------------------------

install_initramfs: ## Embed tiny shell initramfs into kernel
	$(call require,$(INITRAMFS_CPIO),Run make_initramfs_tiny_shell first.)
	$(KCONFIG) --set-str CONFIG_INITRAMFS_SOURCE $(INITRAMFS_CPIO)
	$(KERNEL_MAKE) olddefconfig
	$(KERNEL_MAKE) $(KERNEL_TARGETS)
	@echo "Kernel with embedded tiny shell initramfs: $(KERNEL_IMAGE)"

# ---------------------------------------------------------------------------
# OpenSBI firmware
# ---------------------------------------------------------------------------

build_opensbi: opensbi ## Build OpenSBI firmware
	$(OPENSBI_MAKE)

build_opensbi_with_kernel: opensbi ## Build OpenSBI with kernel payload
	python3 scripts/prepare-opensbi.py --output "$(OPENSBI_OBJDIR)" \
		--kernel "$(KERNEL_IMAGE)" --bits "$(BITS)" --isa "$(RISCV_ISA)" \
		--cross-compile "$(CROSS_COMPILE)" --fdt-offset "$(FW_PAYLOAD_FDT_OFFSET)"
	$(OPENSBI_MAKE) FW_PAYLOAD_PATH=$(KERNEL_IMAGE) FW_PAYLOAD_FDT_OFFSET=$(FW_PAYLOAD_FDT_OFFSET)
	@mv $(OPENSBI_OBJDIR)/.build-inputs.pending.json $(OPENSBI_OBJDIR)/.build-inputs.json

# ---------------------------------------------------------------------------
# QEMU tests
# ---------------------------------------------------------------------------
#
# test_qemu:        boot the self-contained fw_payload (OpenSBI + kernel embedded)
# test_qemu_kernel: boot OpenSBI fw_dynamic + separate kernel Image + initramfs
#                   (useful to iterate without rebuilding firmware)

QEMU_BASE    := qemu-system-riscv$(BITS) -M virt -m $(QEMU_MEM)M -nographic
QEMU_TINY_NET := -netdev user,id=net0 -device virtio-net-device,netdev=net0

test_qemu: ## Boot fw_payload.bin in QEMU
	$(call require,$(FW_PAYLOAD_BIN),Run build_opensbi_with_kernel first.)
	$(IF_TIMEOUT) $(QEMU_BASE) -bios $(FW_PAYLOAD_BIN)

test_qemu_kernel: ## Boot kernel, initramfs, and fw_dynamic in QEMU
	$(call require,$(KERNEL_IMAGE),Run build_linux first.)
	$(call require,$(INITRAMFS_CPIO),Run make_initramfs_tiny_shell first.)
	$(IF_TIMEOUT) $(QEMU_BASE) $(QEMU_TINY_NET) $(QEMU_KERNEL_ARGS)

# ---------------------------------------------------------------------------
# Spike tests
#
# Uses the locally-built Spike when spike-build/bin/spike exists (via build_spike),
# otherwise falls back to the system 'spike' in PATH.
# The generic OpenSBI fw_payload.elf works with Spike's built-in HTIF/SBI.
# ---------------------------------------------------------------------------

test_spike: ## Boot fw_payload.elf in Spike
	@test -x $(SPIKE) 2>/dev/null || command -v $(SPIKE) >/dev/null 2>&1 || \
		(echo "ERROR: spike not found. Run 'make build_spike' or install from https://github.com/riscv-software-src/riscv-isa-sim" && false)
	$(call require,$(FW_PAYLOAD_ELF),Run build_opensbi_with_kernel first.)
	$(SPIKE) --isa=$(RISCV_ISA) -m$(SPIKE_MEM) $(FW_PAYLOAD_ELF)

# ---------------------------------------------------------------------------
# Batch and housekeeping
# ---------------------------------------------------------------------------

build_all: linux opensbi ## Build RV32 and RV64 tiny shell variants
	$(MAKE) BITS=32 build_linux make_initramfs_tiny_shell install_initramfs build_opensbi_with_kernel
	$(MAKE) BITS=64 build_linux make_initramfs_tiny_shell install_initramfs build_opensbi_with_kernel

# ---------------------------------------------------------------------------
# Package and release
#
# Usage:
#   make BITS=32 package   -> linux-riscv-rv32-v<ver>.tar.gz
#   make BITS=64 package   -> linux-riscv-rv64-v<ver>.tar.gz
#   make package_all       -> build + package every preset under configs/
# ---------------------------------------------------------------------------

package: linux opensbi ## Package selected tiny-shell or persistent distribution variant
ifneq ($(filter alpine debian,$(SYSTEM_ROOTFS)),)
	$(MAKE) package_distro
else
	$(MAKE) KERNEL_VARIANT=minimal _package_minimal
endif

_package_minimal: configure_kernel
	$(MAKE) make_initramfs_tiny_shell
	$(KCONFIG) --set-str CONFIG_INITRAMFS_SOURCE $(INITRAMFS_CPIO)
	$(KERNEL_MAKE) olddefconfig
	$(KERNEL_MAKE) $(KERNEL_TARGETS)
	$(MAKE) build_opensbi_with_kernel
	python3 scripts/package-artifacts.py --dist "$(DIST_DIR)" --name "$(RELEASE_NAME)" \
		--kernel-dir "$(OBJDIR)" --firmware-dir "$(OPENSBI_OBJDIR)/platform/generic/firmware" \
		--initramfs "$(INITRAMFS_CPIO)" --preset "configs/$(SYSTEM_PRESET).toml" \
		--variant tiny_shell --isa "$(RISCV_ISA)" --abi "$(RISCV_ABI)" \
		--fdt-offset "$(FW_PAYLOAD_FDT_OFFSET)"

package_all: ## Build all presets into a release candidate without deleting old packages
	python3 scripts/build-release.py --dist "$(DIST_DIR)" --jobs "$(NPROC)" --build-root "$(RELEASE_BUILD_ROOT)" $(if $(filter 1,$(RELEASE_RESUME)),--resume,)

test_all: ## Validate and boot split/payload paths for every release package
	python3 scripts/test-packages.py --dist "$(DIST_DIR)" --timeout $(PACKAGE_TEST_TIMEOUT) --jobs $(PACKAGE_TEST_JOBS)

release_ready: test_all ## Validate the candidate and write checksums/release notes
	python3 scripts/check-release.py --dist "$(DIST_DIR)" --write

# ---------------------------------------------------------------------------
# GitHub release
# Requires the 'gh' CLI: https://cli.github.com
#
# Usage:
#   make github_release					# tag from qemu-rv64.toml; title from dist versions
#   make github_release TAG=rv-v6.18.50  # custom tag
#
# All tarballs must exist (run 'make package_all' first).
# ---------------------------------------------------------------------------

TAG ?=## GitHub release tag (empty = derive from configs/qemu-rv64.toml)

github_release: ## Create GitHub release and upload validated tarballs
	python3 scripts/check-release.py --dist "$(DIST_DIR)"
	$(call require_cmd,gh,Install from https://cli.github.com)
	@set -euo pipefail; \
		release_files=("$(DIST_DIR)"/*.tar.gz); \
		if [ ! -e "$${release_files[0]}" ]; then \
			echo "ERROR: No tarballs found in dist/. Run 'make package_all' first."; \
			exit 1; \
		fi; \
		mapfile -t versions < <(printf '%s\n' "$${release_files[@]}" | \
			sed -n 's/.*-v\([^/]*\)\.tar\.gz$$/\1/p' | sort -Vu); \
		if [ "$${#versions[@]}" -eq 0 ]; then \
			echo "ERROR: Cannot determine kernel versions from dist tarball names."; \
			exit 1; \
		fi; \
		version_label=$$(printf '%s / ' "$${versions[@]}"); \
		version_label=$${version_label% / }; \
		release_title="Linux $$version_label for RISC-V"; \
		release_tag="$(TAG)"; \
		if [ -z "$$release_tag" ]; then \
			tag_version=$$(python3 -c 'import tomllib; print(tomllib.load(open("configs/qemu-rv64.toml", "rb"))["kernel"]["version"])'); \
			if ! printf '%s\n' "$${versions[@]}" | grep -Fqx "$$tag_version"; then \
				echo "ERROR: qemu-rv64.toml version $$tag_version is absent from dist tarballs."; \
				exit 1; \
			fi; \
			release_tag="rv-v$$tag_version"; \
		fi; \
		echo "--- Creating GitHub Release $$release_tag ---"; \
		echo "Title: $$release_title"; \
		gh release create "$$release_tag" \
			"$${release_files[@]}" \
			--title "$$release_title" \
			"$(DIST_DIR)/SHA256SUMS" "$(DIST_DIR)/release-ready.json" "$(DIST_DIR)/test-results.json" \
			--notes-file "$(DIST_DIR)/release-notes.md"; \
		echo "Release $$release_tag published."

clean_packages: ## Remove release tarballs
	rm -rf $(PWD_DIR)/dist
	@echo "dist/ removed."

# ---------------------------------------------------------------------------
# Housekeeping
# ---------------------------------------------------------------------------

clean: ## Remove build artifacts and generated configs
	rm -rf linux/ build32 build64 \
		initramfs32 initramfs64 initramfs32.cpio.gz initramfs64.cpio.gz \
		initramfs32.list initramfs64.list \
		initramfs32-buildroot.cpio.gz initramfs64-buildroot.cpio.gz \
		initramfs32-buildroot.stamp initramfs64-buildroot.stamp \
		opensbi opensbi-build32 opensbi-build64 \
		payload/build payload/init payload/init_shell \
		.config.mk .config.kernel .config.kernel.minimal .config.kernel.buildroot .config.buildroot

clean_spike: ## Remove Spike source and build directories
	rm -rf spike spike-build

.PHONY: help all \
        configure build test clean_config \
        linux opensbi spike_src \
        build_linux configure_kernel _package_minimal \
		build_init make_initramfs_tiny_shell \
		install_initramfs \
        build_opensbi build_opensbi_with_kernel build_spike \
		test_qemu test_qemu_kernel test_spike \
        build_all clean clean_spike \
		package package_all test_all release_ready github_release clean_packages
