# scripts/buildroot.mk — Buildroot-related targets and variables
#
# Included by the top-level Makefile.  All variables defined there
# (PWD_DIR, BITS, KERNEL_VERSION, CROSS_COMPILE, OBJDIR, KCONFIG,
#  KERNEL_MAKE, KERNEL_IMAGE, FW_*, QEMU_BASE, IF_TIMEOUT, NPROC, …)
# are available here.
# ---------------------------------------------------------------------------

# Per-bitness Buildroot initramfs CPIO
BUILDROOT_CPIO := $(PWD_DIR)/initramfs$(BITS)-buildroot.cpio.gz
# Stamp file: hash of .config.buildroot used for the last buildroot build
BUILDROOT_STAMP := $(PWD_DIR)/initramfs$(BITS)-buildroot.stamp

# Buildroot per-bitness clone directory
BUILDROOT_DIR  := $(PWD_DIR)/buildroot$(BITS)
# Buildroot config fragment generated by: make configure SYSTEM=configs/<preset>.toml
BUILDROOT_CFG  := $(PWD_DIR)/.config.buildroot

# Buildroot release package (distinct from tiny shell initramfs package)
ifneq ($(SYSTEM_PRESET),)
  BUILDROOT_RELEASE_NAME    := linux-riscv-rv$(BITS)-$(SYSTEM_PRESET)-buildroot-v$(KERNEL_VERSION)
else
  BUILDROOT_RELEASE_NAME    := linux-riscv-rv$(BITS)-buildroot-v$(KERNEL_VERSION)
endif
BUILDROOT_RELEASE_TARBALL := $(DIST_DIR)/$(BUILDROOT_RELEASE_NAME).tar.gz
BUILDROOT_RELEASE_STAGING := $(DIST_DIR)/$(BUILDROOT_RELEASE_NAME)

# QEMU kernel boot arguments for Buildroot (uses BUILDROOT_CPIO)
QEMU_KERNEL_BUILDROOT_ARGS = \
	-bios $(FW_DYNAMIC_BIN) \
	-kernel $(KERNEL_IMAGE) \
	-initrd $(BUILDROOT_CPIO) \
	-append "root=/dev/ram rdinit=/init console=ttyS0 earlycon=sbi"

# Networking for buildroot variants: virtio-net with user-mode NAT + SSH forwarding
SSH_PORT ?= 2222## Host SSH forwarding port for Buildroot QEMU targets
QEMU_NET := -netdev user,id=net0,hostfwd=tcp::$(SSH_PORT)-:22 \
            -device virtio-net-device,netdev=net0

# Optional 9P host directory share (set SHARE_DIR=/path to enable)
# Set SHARE_RO=1 to mount read-only (prevents guest from writing to host)
SHARE_DIR ?=## Host directory to expose over 9P in Buildroot QEMU targets
SHARE_RO ?=## Set to 1 to mount SHARE_DIR read-only
comma := ,
QEMU_SHARE_RW = $(if $(SHARE_DIR),-fsdev local$(comma)id=fsdev0$(comma)path=$(SHARE_DIR)$(comma)security_model=mapped \
                -device virtio-9p-device$(comma)fsdev=fsdev0$(comma)mount_tag=hostshare)
QEMU_SHARE_RO = $(if $(SHARE_DIR),-fsdev local$(comma)id=fsdev0$(comma)path=$(SHARE_DIR)$(comma)security_model=mapped$(comma)readonly=on \
                -device virtio-9p-device$(comma)fsdev=fsdev0$(comma)mount_tag=hostshare)
QEMU_SHARE = $(if $(SHARE_RO),$(QEMU_SHARE_RO),$(QEMU_SHARE_RW))

# ---------------------------------------------------------------------------
# Source acquisition
# ---------------------------------------------------------------------------

buildroot: ## Clone Buildroot source for current BITS
	@if [ -d $(BUILDROOT_DIR) ]; then \
		echo "$(BUILDROOT_DIR) already exists, skipping clone"; \
	else \
		git clone --depth=1 https://github.com/buildroot/buildroot $(BUILDROOT_DIR); \
	fi

# ---------------------------------------------------------------------------
# Buildroot initramfs
# ---------------------------------------------------------------------------

# Incremental Buildroot build: regenerates .config from defconfig + fragment
# but keeps build artefacts for fast incremental rebuilds.
# Use make_initramfs_buildroot_clean for a full from-scratch rebuild.
make_initramfs_buildroot: buildroot ## Build Buildroot initramfs incrementally
	$(call require,$(BUILDROOT_CFG),Run 'make configure SYSTEM=configs/<preset>.toml' first.)
	# (Re)generate .config from defconfig + our config fragment.
	# First strip symbols that our fragment overrides so its values win,
	# even for Kconfig "choice" groups (e.g. BR2_SYSTEM_BIN_SH_BASH).
	make -C $(BUILDROOT_DIR) qemu_riscv$(BITS)_virt_defconfig
	@grep -oE '^(# )?BR2_[A-Za-z0-9_]+' $(BUILDROOT_CFG) | \
	  sed 's/^# //' | sort -u | \
	  while read sym; do \
	    sed -i "/^$${sym}[= ]/d; /^# $${sym} is not set/d" $(BUILDROOT_DIR)/.config; \
	  done
	cat $(BUILDROOT_CFG) >> $(BUILDROOT_DIR)/.config
	make -C $(BUILDROOT_DIR) olddefconfig
	# Upstream QEMU defconfigs used to install modules for a different kernel.
	# The external linux-build kernel supplies all required built-in drivers.
	@if ! grep -q '^BR2_LINUX_KERNEL=y' $(BUILDROOT_DIR)/.config; then \
		rm -rf $(BUILDROOT_DIR)/output/target/lib/modules $(BUILDROOT_DIR)/output/target/usr/lib/modules; \
	fi
	# A newly selected fragment may be older than BusyBox stamps. Reconfigure
	# explicitly instead of relying only on file timestamps.
	make -C $(BUILDROOT_DIR) -j$(NPROC) busybox-reconfigure
	make -C $(BUILDROOT_DIR) -j$(NPROC)
	cp $(BUILDROOT_DIR)/output/images/rootfs.cpio.gz $(BUILDROOT_CPIO)
	# Save config hash so we can detect when a rebuild is needed
	@md5sum $(BUILDROOT_CFG) | cut -d' ' -f1 > $(BUILDROOT_STAMP)
	@echo "Buildroot initramfs: $(BUILDROOT_CPIO)"

# Full clean Buildroot rebuild (slow — use only when incremental gives stale results)
make_initramfs_buildroot_clean: buildroot ## Rebuild Buildroot initramfs from scratch
	make -C $(BUILDROOT_DIR) distclean
	$(MAKE) make_initramfs_buildroot

# Convenience: rebuild Buildroot only (fastest iteration for package changes)
# Boot with: make BITS=$(BITS) test_qemu_kernel_buildroot
update_buildroot: ## Rebuild Buildroot rootfs only
	$(MAKE) make_initramfs_buildroot
	@echo ""
	@echo "Done. Test with:  make BITS=$(BITS) test_qemu_kernel_buildroot"

# Like update_buildroot but also re-embeds initramfs into kernel + rebuilds OpenSBI
# (needed only when booting via fw_payload / test_qemu_buildroot).
update_buildroot_full: ## Rebuild Buildroot, re-embed initramfs, and rebuild OpenSBI
	$(MAKE) ensure_initramfs_buildroot
	$(MAKE) KERNEL_VARIANT=buildroot _install_initramfs_buildroot
	$(MAKE) KERNEL_VARIANT=buildroot RISCV_ISA=$(RISCV_ISA_BUILDROOT) build_opensbi_with_kernel

# ---------------------------------------------------------------------------
# Embed Buildroot initramfs into kernel Image
# ---------------------------------------------------------------------------

ensure_initramfs_buildroot: buildroot ## Reuse a verified rootfs cache or rebuild its configuration
	python3 scripts/ensure-rootfs.py --bits "$(BITS)" --config "$(BUILDROOT_CFG)" --jobs "$(NPROC)"

prepare_kernel_buildroot: linux ## Build the independent Buildroot kernel configuration
	$(MAKE) KERNEL_VARIANT=buildroot build_linux

install_initramfs_buildroot: linux ## Build kernel with embedded Buildroot initramfs
	$(MAKE) KERNEL_VARIANT=buildroot _install_initramfs_buildroot

_install_initramfs_buildroot: configure_kernel
	$(call require,$(BUILDROOT_CPIO),Run ensure_initramfs_buildroot first.)
	$(KCONFIG) --set-str CONFIG_INITRAMFS_SOURCE $(BUILDROOT_CPIO)
	$(KERNEL_MAKE) olddefconfig
	$(KERNEL_MAKE) $(KERNEL_TARGETS)

# ---------------------------------------------------------------------------
# QEMU Buildroot tests
# ---------------------------------------------------------------------------

# Buildroot variants: add virtio-net (eth0 + SSH) and optional 9P host share.
# SSH from host:  ssh root@localhost -p $(SSH_PORT)
# Host 9P share:  make SHARE_DIR=/path test_qemu_buildroot
test_qemu_buildroot: ## Boot Buildroot fw_payload in QEMU with networking
	$(MAKE) KERNEL_VARIANT=buildroot QEMU_MEM=$(QEMU_MEM_BUILDROOT) _test_qemu_buildroot

_test_qemu_buildroot:
	$(call require,$(FW_PAYLOAD_BIN),Run package_buildroot first.)
	$(IF_TIMEOUT) $(QEMU_BASE) $(QEMU_NET) $(QEMU_SHARE) -bios $(FW_PAYLOAD_BIN)

test_qemu_kernel_buildroot: ## Boot independent Buildroot kernel and initramfs in QEMU
	$(MAKE) KERNEL_VARIANT=buildroot QEMU_MEM=$(QEMU_MEM_BUILDROOT) _test_qemu_kernel_buildroot

_test_qemu_kernel_buildroot:
	$(call require,$(KERNEL_IMAGE),Run install_initramfs_buildroot first.)
	$(call require,$(FW_DYNAMIC_BIN),Run package_buildroot first.)
	$(IF_TIMEOUT) $(QEMU_BASE) $(QEMU_NET) $(QEMU_SHARE) $(QEMU_KERNEL_BUILDROOT_ARGS)

test_qemu_buildroot_shell: ## Boot a fast Buildroot shell with runtime filesystems mounted
	$(MAKE) KERNEL_VARIANT=buildroot QEMU_MEM=$(QEMU_MEM_BUILDROOT) _test_qemu_buildroot_shell

_test_qemu_buildroot_shell:
	$(call require,$(KERNEL_IMAGE),Run package_buildroot first.)
	$(call require,$(FW_DYNAMIC_BIN),Run package_buildroot first.)
	$(call require,$(BUILDROOT_CPIO),Run package_buildroot first.)
	$(IF_TIMEOUT) $(QEMU_BASE) $(QEMU_NET) $(QEMU_SHARE) \
		-bios $(FW_DYNAMIC_BIN) -kernel $(KERNEL_IMAGE) -initrd $(BUILDROOT_CPIO) \
		-append "root=/dev/ram rdinit=/sbin/raptor-shell console=ttyS0 earlycon=sbi ip=dhcp"

# ---------------------------------------------------------------------------
# Package Buildroot artifacts
# ---------------------------------------------------------------------------

package_buildroot: linux opensbi ## Package Buildroot artifacts from an independent kernel configuration
	$(MAKE) ensure_initramfs_buildroot
	$(MAKE) KERNEL_VARIANT=buildroot _package_buildroot

_package_buildroot: _install_initramfs_buildroot
	$(MAKE) RISCV_ISA=$(RISCV_ISA_BUILDROOT) build_opensbi_with_kernel
	python3 scripts/package-artifacts.py --dist "$(DIST_DIR)" --name "$(BUILDROOT_RELEASE_NAME)" \
		--kernel-dir "$(OBJDIR)" --firmware-dir "$(OPENSBI_OBJDIR)/platform/generic/firmware" \
		--initramfs "$(BUILDROOT_CPIO)" --preset "configs/$(SYSTEM_PRESET).toml" \
		--variant buildroot --isa "$(RISCV_ISA_BUILDROOT)" --abi "$(RISCV_ABI_BUILDROOT)" \
		--fdt-offset "$(FW_PAYLOAD_FDT_OFFSET)"

# ---------------------------------------------------------------------------
# Housekeeping
# ---------------------------------------------------------------------------

clean_buildroot: ## Remove Buildroot clone directories
	rm -rf buildroot32 buildroot64

.PHONY: ensure_initramfs_buildroot _install_initramfs_buildroot _package_buildroot _test_qemu_buildroot _test_qemu_kernel_buildroot buildroot \
        make_initramfs_buildroot make_initramfs_buildroot_clean \
	prepare_kernel_buildroot install_initramfs_buildroot \
        update_buildroot update_buildroot_full \
        test_qemu_buildroot test_qemu_kernel_buildroot \
        package_buildroot clean_buildroot

.PHONY: test_qemu_buildroot_shell _test_qemu_buildroot_shell
